#include <boost/locale.hpp>
#include <boost/algorithm/string.hpp>
#include <fstream>
#include <memory>
#include <stdint.h>
#include <stdlib.h>
#include <string>
#include <vector>
#include <Wt/WApplication>
#include <Wt/WContainerWidget>
#include <Wt/WDatePicker>
#include <Wt/WDialog>
#include <Wt/WEnvironment>
#include <Wt/WFileUpload>
#include <Wt/WGridLayout>
#include <Wt/WGroupBox>
#include <Wt/WHBoxLayout>
#include <Wt/WImage>
#include <Wt/WLength>
#include <Wt/WLineEdit>
#include <Wt/WLocalizedStrings>
#include <Wt/WProgressBar>
#include <Wt/WPushButton>
#include <Wt/WSelectionBox>
#include <Wt/WString>
#include <Wt/WTabWidget>
#include <Wt/WText>
#include <Wt/WVBoxLayout>
#include <Wt/Auth/HashFunction>
#include <Poco/Bugcheck.h>
#include <Poco/Nullable.h>
#include <Poco/Timestamp.h>
#include <Poco/Data/SessionPool.h>
